# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: createsecret@1
    inputs:
      azureSubscription: 'Free Trial (f1e805f7-af66-4c1a-9f8f-4c695ced1b28)'
      KeyVaultName: 'jsofjevbvsogsnvsk'
      SecretName: 'dbpassword'
      SecretValue: 'Password@2704'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'